version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.24.2
    container_name: gloria-temporal
    depends_on:
      - postgresql-temporal
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql-temporal
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    ports:
      - "7233:7233"  # gRPC
    volumes:
      - ./temporal-config:/etc/temporal/config/dynamicconfig
    networks:
      - gloria-temporal-network

  temporal-ui:
    image: temporalio/ui:2.26.2
    container_name: gloria-temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8233:8080"  # Web UI
    networks:
      - gloria-temporal-network

  postgresql-temporal:
    image: postgres:16-alpine
    container_name: gloria-temporal-postgres
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal
    ports:
      - "5433:5432"
    volumes:
      - temporal-postgres-data:/var/lib/postgresql/data
    networks:
      - gloria-temporal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  temporal-postgres-data:
    driver: local

networks:
  gloria-temporal-network:
    driver: bridge
